name: safet3_engine
description: Safet3 engine.
environment:
  sdk: '^3.10.4'
resolution: workspace

dependencies:
  # DÃ©pendance interne vers le core
  safet3_core:
    path: ../safet3_core
  
  # Pour lire le format YAML
  yaml: ^3.1.3
  
  # Utile pour convertir YAML -> JSON
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0